version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./modules:/usr/app/src/modules
      - secrets:/usr/app/src/config
    depends_on:
      - mysql  # Ensure the mysql service starts before python-app
    command: python -u ./main.py

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /usr/app/src/config/database_password.txt
    volumes:
      - secrets:/usr/app/src/config  # Mounting the secrets directory
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"  # Expose MySQL port

volumes:
  secrets:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind