version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./modules:/usr/app/src/modules
      - secrets:/usr/app/src/config
    depends_on:
      mysql:
        condition: service_healthy  # Ensure the mysql service is healthy before starting python-app
    command: python -u ./main.py

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /usr/app/src/config/database_password.txt
    volumes:
      - secrets:/usr/app/src/config  # Mounting the secrets directory
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-init/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"  # Expose MySQL port
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  secrets:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
  mysql-data: